<?php

use Illuminate\Database\Seeder;

class PlansTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('plans')->delete();
        
        \DB::table('plans')->insert(array (
            0 => 
            array (
                'id' => 1,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'SMDWESSMD1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            1 => 
            array (
                'id' => 2,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'SMDWESSMD1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            2 => 
            array (
                'id' => 3,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'SMDWESSMD1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            3 => 
            array (
                'id' => 4,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'SMDWESSMD1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            4 => 
            array (
                'id' => 5,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'SMDWESSMD1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            5 => 
            array (
                'id' => 6,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'SMDWESSMD1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            6 => 
            array (
                'id' => 7,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'SMDWESSMD1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            7 => 
            array (
                'id' => 8,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'SMDWESSMD1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            8 => 
            array (
                'id' => 9,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'SMDWESSMD1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            9 => 
            array (
                'id' => 10,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'SMDWESSMD1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            10 => 
            array (
                'id' => 11,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'SMDWESSMD1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            11 => 
            array (
                'id' => 12,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'SMDWESSMD1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            12 => 
            array (
                'id' => 13,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet Basis',
                'description_long' => 'Internet only, 100 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            13 => 
            array (
                'id' => 14,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet Snel',
                'description_long' => 'Internet only, 250 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            14 => 
            array (
                'id' => 15,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet Supersnel',
                'description_long' => 'Internet only, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            15 => 
            array (
                'id' => 16,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet Ultrasnel',
                'description_long' => 'Internet only, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            16 => 
            array (
                'id' => 17,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet & Bellen Basis',
                'description_long' => 'Internet en Bellen, 100 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            17 => 
            array (
                'id' => 18,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet & Bellen Snel',
                'description_long' => 'Internet en Bellen, 250 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            18 => 
            array (
                'id' => 19,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet & Bellen Supersnel',
                'description_long' => 'Internet en Bellen, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            19 => 
            array (
                'id' => 20,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet & Bellen Ultrasnel',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            20 => 
            array (
                'id' => 21,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet Basis',
                'description_long' => 'Internet only, 100 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            21 => 
            array (
                'id' => 22,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet Snel',
                'description_long' => 'Internet only, 250 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            22 => 
            array (
                'id' => 23,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet Supersnel',
                'description_long' => 'Internet only, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            23 => 
            array (
                'id' => 24,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet Ultrasnel',
                'description_long' => 'Internet only, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            24 => 
            array (
                'id' => 25,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet & Bellen Basis',
                'description_long' => 'Internet en Bellen, 100 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            25 => 
            array (
                'id' => 26,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet & Bellen Snel',
                'description_long' => 'Internet en Bellen, 250 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            26 => 
            array (
                'id' => 27,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet & Bellen Supersnel',
                'description_long' => 'Internet en Bellen, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            27 => 
            array (
                'id' => 28,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'CAHCAH0001',
                'project_id' => NULL,
                'description' => 'Internet & Bellen Ultrasnel',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            28 => 
            array (
                'id' => 29,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESRAS1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            29 => 
            array (
                'id' => 30,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESRAS1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            30 => 
            array (
                'id' => 31,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESRAS1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            31 => 
            array (
                'id' => 32,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESRAS1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            32 => 
            array (
                'id' => 33,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESRAS1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            33 => 
            array (
                'id' => 34,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESRAS1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            34 => 
            array (
                'id' => 35,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESRAS1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            35 => 
            array (
                'id' => 36,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESRAS1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            36 => 
            array (
                'id' => 37,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESRAS1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            37 => 
            array (
                'id' => 38,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESRAS1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            38 => 
            array (
                'id' => 39,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESRAS1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            39 => 
            array (
                'id' => 40,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESRAS1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            40 => 
            array (
                'id' => 41,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESBVH1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            41 => 
            array (
                'id' => 42,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESBVH1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            42 => 
            array (
                'id' => 43,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESBVH1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            43 => 
            array (
                'id' => 44,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESBVH1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            44 => 
            array (
                'id' => 45,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESBVH1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            45 => 
            array (
                'id' => 46,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESBVH1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            46 => 
            array (
                'id' => 47,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESBVH1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            47 => 
            array (
                'id' => 48,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESBVH1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            48 => 
            array (
                'id' => 49,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESBVH1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            49 => 
            array (
                'id' => 50,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESBVH1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            50 => 
            array (
                'id' => 51,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESBVH1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            51 => 
            array (
                'id' => 52,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESBVH1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            52 => 
            array (
                'id' => 53,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESGVN1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            53 => 
            array (
                'id' => 54,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESGVN1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            54 => 
            array (
                'id' => 55,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESGVN1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            55 => 
            array (
                'id' => 56,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESGVN1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            56 => 
            array (
                'id' => 57,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESGVN1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            57 => 
            array (
                'id' => 58,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESGVN1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            58 => 
            array (
                'id' => 59,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESGVN1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            59 => 
            array (
                'id' => 60,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESGVN1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            60 => 
            array (
                'id' => 61,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESGVN1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            61 => 
            array (
                'id' => 62,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESGVN1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            62 => 
            array (
                'id' => 63,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESGVN1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            63 => 
            array (
                'id' => 64,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESGVN1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            64 => 
            array (
                'id' => 65,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESDLZ1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            65 => 
            array (
                'id' => 66,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESDLZ1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            66 => 
            array (
                'id' => 67,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESDLZ1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            67 => 
            array (
                'id' => 68,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESDLZ1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            68 => 
            array (
                'id' => 69,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESDLZ1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            69 => 
            array (
                'id' => 70,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESDLZ1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            70 => 
            array (
                'id' => 71,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESDLZ1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            71 => 
            array (
                'id' => 72,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESDLZ1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            72 => 
            array (
                'id' => 73,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESDLZ1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            73 => 
            array (
                'id' => 74,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESDLZ1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            74 => 
            array (
                'id' => 75,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESDLZ1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            75 => 
            array (
                'id' => 76,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESDLZ1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            76 => 
            array (
                'id' => 77,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESOSD1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            77 => 
            array (
                'id' => 78,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESOSD1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            78 => 
            array (
                'id' => 79,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESOSD1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            79 => 
            array (
                'id' => 80,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESOSD1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            80 => 
            array (
                'id' => 81,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESOSD1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            81 => 
            array (
                'id' => 82,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESOSD1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            82 => 
            array (
                'id' => 83,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESOSD1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            83 => 
            array (
                'id' => 84,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESOSD1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            84 => 
            array (
                'id' => 85,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESOSD1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            85 => 
            array (
                'id' => 86,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESOSD1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            86 => 
            array (
                'id' => 87,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESOSD1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            87 => 
            array (
                'id' => 88,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GVNWESOSD1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            88 => 
            array (
                'id' => 89,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'MBGAQSMBG1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            89 => 
            array (
                'id' => 90,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'MBGAQSMBG1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            90 => 
            array (
                'id' => 91,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'MBGAQSMBG1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            91 => 
            array (
                'id' => 92,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'MBGAQSMBG1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            92 => 
            array (
                'id' => 93,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'MBGAQSMBG1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            93 => 
            array (
                'id' => 94,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'MBGAQSMBG1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            94 => 
            array (
                'id' => 95,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'MBGAQSMBG1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            95 => 
            array (
                'id' => 96,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'MBGAQSMBG1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            96 => 
            array (
                'id' => 97,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'MBGAQSMBG1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            97 => 
            array (
                'id' => 98,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'MBGAQSMBG1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            98 => 
            array (
                'id' => 99,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'MBGAQSMBG1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            99 => 
            array (
                'id' => 100,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'MBGAQSMBG1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            100 => 
            array (
                'id' => 101,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'KPGAQSKPG1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            101 => 
            array (
                'id' => 102,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'KPGAQSKPG1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            102 => 
            array (
                'id' => 103,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'KPGAQSKPG1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            103 => 
            array (
                'id' => 104,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'KPGAQSKPG1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            104 => 
            array (
                'id' => 105,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'KPGAQSKPG1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            105 => 
            array (
                'id' => 106,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'KPGAQSKPG1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            106 => 
            array (
                'id' => 107,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'KPGAQSKPG1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            107 => 
            array (
                'id' => 108,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'KPGAQSKPG1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            108 => 
            array (
                'id' => 109,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'KPGAQSKPG1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            109 => 
            array (
                'id' => 110,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'KPGAQSKPG1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            110 => 
            array (
                'id' => 111,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'KPGAQSKPG1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            111 => 
            array (
                'id' => 112,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'KPGAQSKPG1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            112 => 
            array (
                'id' => 113,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'BFRAQSDVR1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            113 => 
            array (
                'id' => 114,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'BFRAQSDVR1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            114 => 
            array (
                'id' => 115,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'BFRAQSDVR1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            115 => 
            array (
                'id' => 116,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'BFRAQSDVR1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            116 => 
            array (
                'id' => 117,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'BFRAQSDVR1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            117 => 
            array (
                'id' => 118,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'BFRAQSDVR1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 500 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            118 => 
            array (
                'id' => 119,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'BFRAQSDVR1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            119 => 
            array (
                'id' => 120,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'BFRAQSDVR1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            120 => 
            array (
                'id' => 121,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'BFRAQSDVR1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            121 => 
            array (
                'id' => 122,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'BFRAQSDVR1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            122 => 
            array (
                'id' => 123,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'BFRAQSDVR1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            123 => 
            array (
                'id' => 124,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'BFRAQSDVR1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 500 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            124 => 
            array (
                'id' => 125,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GDWCMBGDW1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            125 => 
            array (
                'id' => 126,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GDWCMBGDW1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            126 => 
            array (
                'id' => 127,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GDWCMBGDW1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            127 => 
            array (
                'id' => 128,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GDWCMBGDW1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            128 => 
            array (
                'id' => 129,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GDWCMBGDW1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            129 => 
            array (
                'id' => 130,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GDWCMBGDW1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 1000 Mbps, 12 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            130 => 
            array (
                'id' => 131,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GDWCMBGDW1',
                'project_id' => NULL,
                'description' => 'Internet',
                'description_long' => 'Internet only, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            131 => 
            array (
                'id' => 132,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GDWCMBGDW1',
                'project_id' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => 'Internet en Bellen, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            132 => 
            array (
                'id' => 133,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GDWCMBGDW1',
                'project_id' => NULL,
                'description' => 'Internet & TV',
                'description_long' => 'Internet en Interactieve TV start, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            133 => 
            array (
                'id' => 134,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GDWCMBGDW1',
                'project_id' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => 'All-in One Light, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            134 => 
            array (
                'id' => 135,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GDWCMBGDW1',
                'project_id' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => 'All-in One Medium, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
            135 => 
            array (
                'id' => 136,
                'tenant_id' => 7,
                'parent_plan' => NULL,
                'plan_type' => NULL,
                'area_code_id' => 'GDWCMBGDW1',
                'project_id' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => 'All-in One Top, 1000 Mbps, 24 mnd',
                'plan_start' => NULL,
                'plan_stop' => NULL,
                'created_at' => '2019-07-09 09:10:11',
                'updated_at' => '2019-07-09 09:10:11',
            ),
        ));
        
        
    }
}