<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '32E',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            1 => 
            array (
                'id' => 2,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
            'description' => 'Set-Top Box HD (bruikleen)',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0450SGI',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            2 => 
            array (
                'id' => 3,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Glasvezelaansluiting',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '32',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            3 => 
            array (
                'id' => 4,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet 1000/1000 Mb',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '96',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            4 => 
            array (
                'id' => 5,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Digitale Televisie HD',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0110SG',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            5 => 
            array (
                'id' => 6,
                'product_type_id' => NULL,
                'serialized' => 'N',
                'status' => NULL,
                'description' => 'TV Pakket - Basis',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0114SG',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => 'm7',
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            6 => 
            array (
                'id' => 7,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
            'description' => 'Opnemen basis (gratis)',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0142SGI',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            7 => 
            array (
                'id' => 8,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
            'description' => 'FOX Sports 1 (gratis)',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0162SGI',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            8 => 
            array (
                'id' => 9,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Goedkoop bellen',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '200',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            9 => 
            array (
                'id' => 10,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Telefoonnummer',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '210',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            10 => 
            array (
                'id' => 11,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
            'description' => 'Wifi Router (bruikleen)',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '412',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            11 => 
            array (
                'id' => 12,
                'product_type_id' => NULL,
                'serialized' => 'Y',
                'status' => NULL,
            'description' => 'Set-Top Box HD (bruikleen)',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0450SG',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => 'm7',
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            12 => 
            array (
                'id' => 13,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Apparatuur borg',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '402',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            13 => 
            array (
                'id' => 14,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet & TV',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '32C',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            14 => 
            array (
                'id' => 15,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Start',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0112SG',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            15 => 
            array (
                'id' => 16,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '7E',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            16 => 
            array (
                'id' => 17,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'FOX Sports Eredivisie pakket',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0150SG',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => 'm7',
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            17 => 
            array (
                'id' => 18,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Glasvezelaansluiting',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '7',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            18 => 
            array (
                'id' => 19,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '32A',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            19 => 
            array (
                'id' => 20,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '32F',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            20 => 
            array (
                'id' => 21,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
            'description' => 'Digitaal Plus Pakket (gratis)',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0130SGI',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            21 => 
            array (
                'id' => 22,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
            'description' => 'FOX Sports Eredivisie pakket (gratis)',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0150SGI',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => 'm7',
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            22 => 
            array (
                'id' => 23,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
            'description' => 'Kaspersky Total Security 1 computer (bij pakket)',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0480I',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            23 => 
            array (
                'id' => 24,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '32D',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            24 => 
            array (
                'id' => 25,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '31B',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            25 => 
            array (
                'id' => 26,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Glasvezelaansluiting',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '31',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            26 => 
            array (
                'id' => 27,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet 500/500 Mb',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '56',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            27 => 
            array (
                'id' => 28,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'CAI Harderwijk BASIS',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '6A100',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            28 => 
            array (
                'id' => 29,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'CAI Harderwijk TV Basispakket',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0110CAIH',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            29 => 
            array (
                'id' => 30,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'CAI Harderwijk aansluiting',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '6',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            30 => 
            array (
                'id' => 31,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet 100/100 Mb',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '14',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            31 => 
            array (
                'id' => 32,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
            'description' => 'Internet (actie)',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '32AI',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            32 => 
            array (
                'id' => 33,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'All-in-One Medium',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '31E',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            33 => 
            array (
                'id' => 34,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Digitaal Plus Pakket',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0130SG',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            34 => 
            array (
                'id' => 35,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'HD pakket',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0180SG',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            35 => 
            array (
                'id' => 36,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '31D',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            36 => 
            array (
                'id' => 37,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '32B',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            37 => 
            array (
                'id' => 38,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'De eerste 12 maanden 5 euro korting',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '7DISC05',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            38 => 
            array (
                'id' => 39,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Ziggo Sport Totaal',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0124SG',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            39 => 
            array (
                'id' => 40,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Onbeperkt Bellen Vast & Mobiel pakket',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '260',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            40 => 
            array (
                'id' => 41,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '31F',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            41 => 
            array (
                'id' => 42,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Onbeperkt Vrij Bellen',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '240',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            42 => 
            array (
                'id' => 43,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Goedkoop bellen',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '200CAIH',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            43 => 
            array (
                'id' => 44,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'HDTV Pluspakket',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0182CAIH',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            44 => 
            array (
                'id' => 45,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Opnemen basis',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0142SG',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            45 => 
            array (
                'id' => 46,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'All-in-One Light',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '7D',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            46 => 
            array (
                'id' => 47,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Premium pakket',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0148CAIH',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            47 => 
            array (
                'id' => 48,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Film 1',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0128SG',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => 'm7',
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            48 => 
            array (
                'id' => 49,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '7A',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            49 => 
            array (
                'id' => 50,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Kaspersky Total Security 1 computer',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '480',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            50 => 
            array (
                'id' => 51,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Kaspersky Total Security 3 computers',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '481',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            51 => 
            array (
                'id' => 52,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Opnemen plus',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0144SG',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            52 => 
            array (
                'id' => 53,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet & TV',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '31C',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            53 => 
            array (
                'id' => 54,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
            'description' => 'Opnemen plus (upgrade van basis)',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0144SGU',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            54 => 
            array (
                'id' => 55,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Onbeperkt Bellen NL & Buitenland Vast Pakket',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '280',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            55 => 
            array (
                'id' => 56,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Kaspersky Total Security 5 computers',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '483',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            56 => 
            array (
                'id' => 57,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'CAI Harderwijk SNEL',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '6A250',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            57 => 
            array (
                'id' => 58,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet 250/250 Mb',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '24',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            58 => 
            array (
                'id' => 59,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet & Bellen',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '7B',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            59 => 
            array (
                'id' => 60,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'FOX Sports Compleet pakket',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0154SG',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            60 => 
            array (
                'id' => 61,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet 100/100 Mb',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '26',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            61 => 
            array (
                'id' => 62,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Glasvezel modem',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '400',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            62 => 
            array (
                'id' => 63,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet & TV',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '7C',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            63 => 
            array (
                'id' => 64,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '31A',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            64 => 
            array (
                'id' => 65,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Glasvezelaansluiting',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '9',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            65 => 
            array (
                'id' => 66,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet 200/200 Mb',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '36',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            66 => 
            array (
                'id' => 67,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Wifi Router beheer',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '414',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            67 => 
            array (
                'id' => 68,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Sport 1',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0124CAIH',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            68 => 
            array (
                'id' => 69,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Extra Smartcard',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0138CAIH',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            69 => 
            array (
                'id' => 70,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'FOX Sports International pakket',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0152SG',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => 'm7',
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            70 => 
            array (
                'id' => 71,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
            'description' => 'Film 1 (gratis)',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0128SGI',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => 'm7',
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            71 => 
            array (
                'id' => 72,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'All-in-One Top',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '7F',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            72 => 
            array (
                'id' => 73,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'CAI Harderwijk SUPERSNEL',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '6A500',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            73 => 
            array (
                'id' => 74,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Internet 500/500 Mb',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '34',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            74 => 
            array (
                'id' => 75,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'FOX Sports 1',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0162SG',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            75 => 
            array (
                'id' => 76,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Film 1',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0128CAIH',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            76 => 
            array (
                'id' => 77,
                'product_type_id' => NULL,
                'serialized' => NULL,
                'status' => NULL,
                'description' => 'Reli Select',
                'description_long' => NULL,
                'vendor' => NULL,
                'vendor_partcode' => '0134CAIH',
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => NULL,
                'backend_api' => NULL,
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            77 => 
            array (
                'id' => 78,
                'product_type_id' => 3,
                'serialized' => 'N',
                'status' => 'ACTIVE',
                'description' => 'IPTV Basis Familie',
                'description_long' => '318',
                'vendor' => NULL,
                'vendor_partcode' => NULL,
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => '17.00000',
                'backend_api' => 'm7',
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            78 => 
            array (
                'id' => 79,
                'product_type_id' => 3,
                'serialized' => 'N',
                'status' => 'ACTIVE',
                'description' => 'IPTV Basis Entertainment',
                'description_long' => '319',
                'vendor' => NULL,
                'vendor_partcode' => NULL,
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => '20.00000',
                'backend_api' => 'm7',
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
            79 => 
            array (
                'id' => 80,
                'product_type_id' => 3,
                'serialized' => 'N',
                'status' => 'ACTIVE',
                'description' => 'IPTV Add-on Ziggo Sport',
                'description_long' => '321',
                'vendor' => NULL,
                'vendor_partcode' => NULL,
                'weight' => NULL,
                'ean_code' => NULL,
                'active_from' => NULL,
                'price' => '20.00000',
                'backend_api' => 'm7',
                'created_at' =>'2019-07-09 15:10:00',
                'updated_at' =>'2019-07-09 15:10:00',
            ),
        ));
        
        
    }
}